# Hugo site configuration for the "hugo-resume" theme.

# Basic Configuration
title = "Portfolio"
baseURL = "https://example.com/"
# theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
sections = ["research", "publications", "education", "teaching", "hobbies"]
profileImage = "img/drtho.jpg"
