name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Hugo (use the appropriate Hugo version)
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.139.2'  # Change to the Hugo version you want to use

      # Step 3: Build the Hugo site (creates the public folder)
      - name: Build the Hugo site
        run: hugo --minify  # Build the site into the "public/" directory

      # Step 4: Deploy to GitHub Pages (push the updated public folder to gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Use the GitHub token for authentication
          publish_dir: ./public  # Path to the generated site folder (Hugo's default output folder)
          publish_branch: gh-pages  # Deploy to the 'gh-pages' branch
          target_branch: gh-pages  # Set target branch to 'gh-pages' (this is where the build gets pushed)
          commit_message: 'Deploy updated site to GitHub Pages'  # Commit message
          allow_empty_commit: false  # Make sure an empty commit is not allowed

