name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Hugo (use the appropriate Hugo version)
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.139.2'  # Change to the Hugo version you want to use

      # Step 3: Build the Hugo site
      - name: Build the Hugo site
        run: hugo --minify  # Builds the site into the "public/" directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Use the PAT secret instead of GITHUB_TOKEN
          publish_dir: ./public  # Path to the generated site folder (Hugo's default output folder)
          branch: main  # Deploy to the 'main' branch
          target_branch: main  # Set target branch to 'main' (this is optional)

