name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main # or the default branch of your repo (e.g., 'master')
    paths:
      - "**/*.md"  # This ensures only markdown files will trigger the build

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.139.2'  # Replace with the version you're using
    
    - name: Build the site
      run: hugo --minify
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Hugo generates the site in the 'public' directory
