name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Set up Hugo (use the appropriate Hugo version)
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.139.2'  # Use the appropriate Hugo version

      # Step 3: Clean up old public folder (ensure there is no leftover content)
      - name: Clean up old public folder
        run: rm -rf ./public

      # Step 4: Build the Hugo site (generate new content)
      - name: Build the Hugo site
        run: hugo --minify

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Use a GitHub token (not GITHUB_TOKEN)
          publish_dir: ./public  # Path to the generated site folder (Hugo's default output folder)
          branch: gh-pages  # Ensure you are deploying to the gh-pages branch
